# Generated by Django 4.1.4 on 2023-01-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe_api", "0002_alter_image_image_alter_image_is_temporary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipestep",
            name="step_text",
            field=models.TextField(max_length=500),
        ),
    ]
