# Generated by Django 4.1.4 on 2023-01-10 16:20

from django.db import migrations, models
import myproject.storage_backends
import recipe_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0005_alter_image_image_alter_recipestep_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, storage=myproject.storage_backends.ClientImageStorage(), upload_to=recipe_api.models.get_file_path),
        ),
    ]
