# Generated by Django 4.1.4 on 2023-02-17 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_api", "0008_alter_image_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment_text",
            new_name="text",
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="ingredient_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="recipe_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="recipestep",
            old_name="step_text",
            new_name="text",
        ),
    ]
