# Generated by Django 4.1.4 on 2023-03-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_api", "0010_alter_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
